export const LightCustomTheme = {
    dark: false,
    colors: {
        primary: 'black',
        secondary: "#EEEEEE",
        background: '#EEEEEE',
        card: '#31363F',
        text: 'black',
        border: 'rgb(199, 199, 204)',
        notification: 'rgb(255, 69, 58)',
        tabBar: '#3D2C8D',
        header: 'white',
        login: "white",
        loginInput: "#EEEEEE",
        cardBackground: "#EEEEEE",
        priceColor: "#008170",
        buyNowColor: "#191A19",
        tabBarBgColor: "#161616",
        tabBarBtActive: "white",
        tabBarBtInActive: "gray",
        loadingColor: "#444444",
        itemCardColor: "white",
        itemCardInfoColor: "#EEEEEE",
    }
}

export const DarkCustomTheme = {
    dark: true,
    colors: {
        primary: 'black',
        secondary: "#0F0F0F",
        background: '#191919',
        card: '#384152',
        text: 'white',
        border: '#0F0F0F',
        notification: 'rgb(255, 69, 58)',
        tabBar: '#3D2C8D',
        header: '#0F0F0F',
        login: "#191A19",
        loginInput: "#31363F",
        cardBackground: "#191919",
        priceColor: "#008170",
        buyNowColor: "#EEEEEE",
        tabBarBgColor: "#31363F",
        tabBarBtActive: "white",
        tabBarBtInActive: "gray",
        loadingColor: "#EEEEEE",
        itemCardColor: "white",
        itemCardInfoColor: "#EEEEEE"
    },
};
